<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="urn:magic.81.21.59.235.DriverPasswordReset"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:tns="urn:magic.81.21.59.235.DriverPasswordReset"
             xmlns:xsdin20="DriverPasswordReset"
             xmlns:xsdout20="DriverPasswordReset"
>

<documentation>
WSDL Builder (Magic eDeveloper v9.4)
Created By   : HITESH---HITESH
Created Date : 24/07/2017 Time :18:31:11
Application   : Import Process
</documentation>

<import  namespace="DriverPasswordReset" location="DriverPasswordResetRequest.xsd"/>
<import  namespace="DriverPasswordReset" location="DriverPasswordResetResponse.xsd"/>

 
<message name="DriverPasswordResetWS">
   <part name="PI_Request_Blob_1" element="xsdin20:PasswordRQ" />
</message>
<message name="DriverPasswordResetWSResponse">
   <part name="DriverPasswordResetWS_Ret"  element="xsdout20:PasswordRS" />
</message>

<portType name="DriverPasswordResetPortType">
         <operation name="DriverPasswordResetWS" >
         <input message="tns:DriverPasswordResetWS" />
         <output message="tns:DriverPasswordResetWSResponse"/>
      </operation>
</portType>

<binding name="DriverPasswordResetBinding"
   type="tns:DriverPasswordResetPortType">
   <soap:binding  transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
         <operation name="DriverPasswordResetWS">
         <documentation></documentation>
         <soap:operation soapAction="357547563756254627F67737371605275667962744F237375636F62705024727F607D694A336F646" />
         <input>
            <soap:body use="literal" />
            
         </input>
         <output>
            <soap:body use="literal" />
         </output>
      </operation>
</binding>
<service name="DriverPasswordReset">
   <documentation></documentation>
   <port name="DriverPasswordResetPortType" binding="tns:DriverPasswordResetBinding">
      <soap:address location="http://81.21.59.235/Magic94Scripts/mgrqispi94.dll" />
   </port>
</service>
</definitions>