<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $table = 'countries';
        DB::table($table)->delete();
        $countries = [
            ['code' => 133, 'name' => 'Australia'],
            ['code' => 134, 'name' => 'UAE'],
            ['code' => 135, 'name' => 'Bahrain'],
            ['code' => 136, 'name' => 'Kuwait'],
            ['code' => 137, 'name' => 'Oman'],
            ['code' => 138, 'name' => 'Qatar'],
            ['code' => 139, 'name' => 'Saudi Arabia'],
            ['code' => 140, 'name' => 'Yemen'],
            ['code' => 142, 'name' => 'Syria'],
            ['code' => 143, 'name' => 'Iraq'],
            ['code' => 144, 'name' => 'Lebanon'],
            ['code' => 145, 'name' => 'Palestine'],
            ['code' => 146, 'name' => 'Egypt'],
            ['code' => 147, 'name' => 'Sudan'],
            ['code' => 148, 'name' => 'Somalia'],
            ['code' => 149, 'name' => 'China'],
            ['code' => 150, 'name' => 'Hong Kong'],
            ['code' => 151, 'name' => 'Indonesia'],
            ['code' => 152, 'name' => 'Japan'],
            ['code' => 155, 'name' => 'Malaysia'],
            ['code' => 156, 'name' => 'Philippines'],
            ['code' => 157, 'name' => 'Singapore'],
            ['code' => 158, 'name' => 'Taiwan'],
            ['code' => 159, 'name' => 'Thailand'],
            ['code' => 160, 'name' => 'India'],
            ['code' => 161, 'name' => 'Iran'],
            ['code' => 162, 'name' => 'Pakistan'],
            ['code' => 163, 'name' => 'Bangladesh'],
            ['code' => 164, 'name' => 'Afghanistan'],
            ['code' => 165, 'name' => 'Sri Lanka'],
            ['code' => 166, 'name' => 'New Zealand'],
            ['code' => 167, 'name' => 'Burundi'],
            ['code' => 168, 'name' => 'Kenya'],
            ['code' => 169, 'name' => 'Malawi'],
            ['code' => 170, 'name' => 'Rwanda'],
            ['code' => 171, 'name' => 'Tanzania'],
            ['code' => 172, 'name' => 'Uganda'],
            ['code' => 173, 'name' => 'Zambia'],
            ['code' => 174, 'name' => 'Zimbabwe'],
            ['code' => 176, 'name' => 'UK'],
            ['code' => 177, 'name' => 'Ireland'],
            ['code' => 178, 'name' => 'France'],
            ['code' => 179, 'name' => 'Germany'],
            ['code' => 180, 'name' => 'Switzerland'],
            ['code' => 181, 'name' => 'Austria'],
            ['code' => 182, 'name' => 'Italy'],
            ['code' => 183, 'name' => 'Spain'],
            ['code' => 184, 'name' => 'Belgium'],
            ['code' => 185, 'name' => 'Netherlands'],
            ['code' => 186, 'name' => 'Norway'],
            ['code' => 187, 'name' => 'Sweden'],
            ['code' => 188, 'name' => 'Denmark'],
            ['code' => 189, 'name' => 'Finland'],
            ['code' => 190, 'name' => 'Armenia'],
            ['code' => 191, 'name' => 'Azerbaijan'],
            ['code' => 192, 'name' => 'Belarus'],
            ['code' => 193, 'name' => 'Georgia'],
            ['code' => 194, 'name' => 'Kazakhstan'],
            ['code' => 195, 'name' => 'Kyrghyzstan'],
            ['code' => 196, 'name' => 'Moldova'],
            ['code' => 197, 'name' => 'Russia'],
            ['code' => 198, 'name' => 'Tadjikistan'],
            ['code' => 199, 'name' => 'Turkmenistan'],
            ['code' => 200, 'name' => 'Ukraine'],
            ['code' => 201, 'name' => 'Uzbekistan'],
            ['code' => 202, 'name' => 'Estonia'],
            ['code' => 203, 'name' => 'Latvia'],
            ['code' => 204, 'name' => 'Lithuania'],
            ['code' => 205, 'name' => 'USA'],
            ['code' => 206, 'name' => 'Canada'],
            ['code' => 207, 'name' => 'Mexico'],
            ['code' => 208, 'name' => 'American Samoa'],
            ['code' => 209, 'name' => 'Cook Islands'],
            ['code' => 210, 'name' => 'Fiji'],
            ['code' => 211, 'name' => 'Frence Polynesia'],
            ['code' => 212, 'name' => 'Guam'],
            ['code' => 213, 'name' => 'Kiribati'],
            ['code' => 214, 'name' => 'Marshal Islands'],
            ['code' => 215, 'name' => 'Northern Mariana Isl.'],
            ['code' => 216, 'name' => 'Papua New Guinea'],
            ['code' => 217, 'name' => 'Solomon Island'],
            ['code' => 218, 'name' => 'Samoa'],
            ['code' => 219, 'name' => 'Tonga'],
            ['code' => 220, 'name' => 'Tuvalu'],
            ['code' => 221, 'name' => 'Vanuatu'],
            ['code' => 222, 'name' => 'Anguilla'],
            ['code' => 223, 'name' => 'Antigua AND Barbuda'],
            ['code' => 224, 'name' => 'Argentina'],
            ['code' => 225, 'name' => 'Aruba'],
            ['code' => 226, 'name' => 'Bahamas'],
            ['code' => 227, 'name' => 'Barbados'],
            ['code' => 228, 'name' => 'Belize'],
            ['code' => 229, 'name' => 'Bermuda'],
            ['code' => 230, 'name' => 'Bolivia'],
            ['code' => 231, 'name' => 'Bonaire'],
            ['code' => 232, 'name' => 'Brazil'],
            ['code' => 233, 'name' => 'British Virgin Islands'],
            ['code' => 234, 'name' => 'Cayman Island'],
            ['code' => 235, 'name' => 'Chile'],
            ['code' => 236, 'name' => 'Colombia'],
            ['code' => 237, 'name' => 'Costa Rica'],
            ['code' => 238, 'name' => 'Cuba'],
            ['code' => 239, 'name' => 'Curacao'],
            ['code' => 240, 'name' => 'Dominica'],
            ['code' => 241, 'name' => 'Dominican Republic'],
            ['code' => 242, 'name' => 'Ecuador'],
            ['code' => 243, 'name' => 'El Salvador'],
            ['code' => 244, 'name' => 'Grenada'],
            ['code' => 245, 'name' => 'Guadaloupe'],
            ['code' => 246, 'name' => 'Guatelama'],
            ['code' => 247, 'name' => 'Guyana'],
            ['code' => 248, 'name' => 'Haiti'],
            ['code' => 249, 'name' => 'Honduras'],
            ['code' => 250, 'name' => 'Jamaica'],
            ['code' => 251, 'name' => 'Martinique'],
            ['code' => 252, 'name' => 'Montserrat'],
            ['code' => 253, 'name' => 'Nicaragua'],
            ['code' => 254, 'name' => 'Panama'],
            ['code' => 255, 'name' => 'Paraguay'],
            ['code' => 256, 'name' => 'Peru'],
            ['code' => 257, 'name' => 'Puerto Rico'],
            ['code' => 258, 'name' => 'Saba'],
            ['code' => 259, 'name' => 'St. Vincent AND Grenadines'],
            ['code' => 260, 'name' => 'Surinam'],
            ['code' => 261, 'name' => 'St. Ketts-Nevis'],
            ['code' => 262, 'name' => 'Trinidad AND Tobago'],
            ['code' => 263, 'name' => 'Uruguay'],
            ['code' => 264, 'name' => 'Venezuela'],
            ['code' => 266, 'name' => 'Benin'],
            ['code' => 271, 'name' => 'Central African Republic'],
            ['code' => 272, 'name' => 'Chad'],
            ['code' => 273, 'name' => 'Congo Rep. of'],
            ['code' => 274, 'name' => 'Congo, Dem. Rep. of (Zaire)'],
            ['code' => 275, 'name' => 'Equatorial Guinea'],
            ['code' => 276, 'name' => 'Gabon'],
            ['code' => 277, 'name' => 'Gambia'],
            ['code' => 278, 'name' => 'Guinea'],
            ['code' => 279, 'name' => 'Guinea-Bissau'],
            ['code' => 281, 'name' => 'Liberia'],
            ['code' => 282, 'name' => 'Malagasy Republic'],
            ['code' => 283, 'name' => 'Mali'],
            ['code' => 284, 'name' => 'Mozambique'],
            ['code' => 287, 'name' => 'Nigeria'],
            ['code' => 288, 'name' => 'Sao Tome'],
            ['code' => 289, 'name' => 'Senegal'],
            ['code' => 290, 'name' => 'Sierra Leone'],
            ['code' => 291, 'name' => 'Swaziland'],
            ['code' => 292, 'name' => 'Togo'],
            ['code' => 293, 'name' => 'Eritrea'],
            ['code' => 295, 'name' => 'Ethiopia'],
            ['code' => 296, 'name' => 'Madagascar'],
            ['code' => 297, 'name' => 'Mauritius'],
            ['code' => 298, 'name' => 'Reunion'],
            ['code' => 299, 'name' => 'Seychelles'],
            ['code' => 300, 'name' => 'Albania'],
            ['code' => 301, 'name' => 'Bosnia-Herzegovina'],
            ['code' => 302, 'name' => 'Bulgaria'],
            ['code' => 303, 'name' => 'Croatia'],
            ['code' => 304, 'name' => 'Cyprus'],
            ['code' => 305, 'name' => 'Czech Republic'],
            ['code' => 307, 'name' => 'Gilraltar'],
            ['code' => 308, 'name' => 'Greece'],
            ['code' => 309, 'name' => 'Hungary'],
            ['code' => 310, 'name' => 'Iceland'],
            ['code' => 311, 'name' => 'Leichtenstein'],
            ['code' => 312, 'name' => 'Luxembourg'],
            ['code' => 314, 'name' => 'Malta'],
            ['code' => 315, 'name' => 'Monaco'],
            ['code' => 316, 'name' => 'Poland'],
            ['code' => 317, 'name' => 'Romania'],
            ['code' => 318, 'name' => 'San Marino (in Italy)'],
            ['code' => 319, 'name' => 'Slovakia Republic'],
            ['code' => 320, 'name' => 'Slovenia'],
            ['code' => 321, 'name' => 'Turkey'],
            ['code' => 322, 'name' => 'Yugoslavia'],
            ['code' => 323, 'name' => 'Mynmar (Burma)'],
            ['code' => 324, 'name' => 'Cambodia'],
            ['code' => 325, 'name' => 'Macau'],
            ['code' => 326, 'name' => 'Mongolia'],
            ['code' => 327, 'name' => 'Vietnam'],
            ['code' => 328, 'name' => 'Bhutan'],
            ['code' => 329, 'name' => 'Maldives'],
            ['code' => 330, 'name' => 'Nepal'],
            ['code' => 340, 'name' => 'Morocco'],
            ['code' => 341, 'name' => 'Tunisia'],
            ['code' => 342, 'name' => 'Algeria'],
            ['code' => 343, 'name' => 'Libya'],
            ['code' => 344, 'name' => 'Djiboti'],
            ['code' => 345, 'name' => 'South Africa'],
            ['code' => 346, 'name' => 'Angola'],
            ['code' => 348, 'name' => 'Botswana'],
            ['code' => 349, 'name' => 'Burkina Faso'],
            ['code' => 350, 'name' => 'Cameroon Republic'],
            ['code' => 351, 'name' => 'Cape Verde'],
            ['code' => 356, 'name' => 'Cote dlvoire'],
            ['code' => 360, 'name' => 'Ghana'],
            ['code' => 363, 'name' => 'Lesotho'],
            ['code' => 368, 'name' => 'Namibia'],
            ['code' => 369, 'name' => 'Niger'],
            ['code' => 376, 'name' => 'Jordan'],
            ['code' => 378, 'name' => 'Portugal'],
            ['code' => 379, 'name' => 'Comoros'],
            ['code' => 380, 'name' => 'Mauritania'],
            ['code' => 381, 'name' => 'Brunei'],
            ['code' => 382, 'name' => 'United Nations'],
            ['code' => 383, 'name' => 'Korea South'],
            ['code' => 384, 'name' => 'Korea North'],
            ['code' => 385, 'name' => 'Nauru'],
            ['code' => 386, 'name' => 'Israel'],
            ['code' => 387, 'name' => 'Saint Lucia'],
            ['code' => 388, 'name' => 'Andorra'],
            ['code' => 389, 'name' => 'Zaire'],
            ['code' => 390, 'name' => 'Vatican City'],
            ['code' => 391, 'name' => 'Laos'],
            ['code' => 392, 'name' => 'HallEnique'],
        ];
        DB::table($table)->insert($countries);
    }
}
