<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="urn:magic.81.21.59.232.PaymentCreateRequest"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
             xmlns:tns="urn:magic.81.21.59.232.PaymentCreateRequest"
             xmlns:xsdin28="ReservationMobilePayment"
             xmlns:xsdout28="ReservationMobilePayment"
>

<documentation>
WSDL Builder (Magic eDeveloper v9.4)
Created By   : HITESH---HITESH
Created Date : 08/11/2017 Time :18:43:15
Application   : Import Process
</documentation>

<import  namespace="ReservationMobilePayment" location="PaymentCreateRequest.xsd"/>
<import  namespace="ReservationMobilePayment" location="PaymentCreateResponse.xsd"/>

 
<message name="CreatePaymentMobileApp">
   <part name="PI_InBlob_1" element="xsdin28:PayMentRQ" />
</message>
<message name="CreatePaymentMobileAppResponse">
   <part name="CreatePaymentMobileApp_Ret"  element="xsdout28:PAYMENTRS" />
</message>

<portType name="PaymentCreateRequestPortType">
         <operation name="CreatePaymentMobileApp" >
         <input message="tns:CreatePaymentMobileApp" />
         <output message="tns:CreatePaymentMobileAppResponse"/>
      </operation>
</portType>

<binding name="PaymentCreateRequestBinding"
   type="tns:PaymentCreateRequestPortType">
   <soap:binding  transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
         <operation name="CreatePaymentMobileApp">
         <documentation></documentation>
         <soap:operation soapAction="07071456C69626F6D447E656D6971605564716562734F237375636F62705024727F607D694A336F646" />
         <input>
            <soap:body use="literal" />
            
         </input>
         <output>
            <soap:body use="literal" />
         </output>
      </operation>
</binding>
<service name="PaymentCreateRequest">
   <documentation></documentation>
   <port name="PaymentCreateRequestPortType" binding="tns:PaymentCreateRequestBinding">
      <soap:address location="http://81.21.59.232/Magic94Scripts/mgrqispi94.dll" />
   </port>
</service>
</definitions>