<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Administrator (EMBRACE) -->
<definitions 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:tns="urn:magic.81.21.59.236.LoginWS" 
	xmlns:xsdin91="CarProUserLogin" 
	xmlns:xsdout91="CarProUserLogin" 
	targetNamespace="urn:magic.81.21.59.236.LoginWS">
	<import namespace="CarProUserLogin" location="LogInRQ.xsd"/>
	<import namespace="CarProUserLogin" location="LogInRS.xsd"/>
	<message name="LogInWS">
		<part name="V__In_Blob_1" element="xsdin91:LoginRQ"/>
	</message>
	<message name="LogInWSResponse">
		<part name="LogInWS_Ret" element="xsdout91:UserLogOut"/>
	</message>
	<portType name="LoginWSPortType">
		<operation name="LogInWS">
			<input message="tns:LogInWS"/>
			<output message="tns:LogInWSResponse"/>
		</operation>
	</portType>
	<binding name="LoginWSBinding" type="tns:LoginWSPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="LogInWS">
			<documentation/>
			<soap:operation soapAction="3575E69476F6C4F237375636F62705024727F607D694A336F646"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="LoginWS">
		<documentation/>
		<port name="LoginWSPortType" binding="tns:LoginWSBinding">
			<soap:address location="http://81.21.59.236/Magic94Scripts/mgrqispi94.dll"/>
		</port>
	</service>
	<documentation>
WSDL Builder (Magic eDeveloper v9.4)
Created By   : HITESH---HITESH
Created Date : 21/06/2017 Time :17:06:13
Application   : Import Process
</documentation>
</definitions>